<?xml version="1.0" encoding="utf-8"?><Database Name="SCTest" Class="SC_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=SCTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SCTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestedAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IncorporationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoanPurpose" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Industry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Revenue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>